alerts:
  etcd:
    etcdInsufficientMembers:
      annotations:
        message: 'bum-bum'
  kubernetes-system:
    KubeVersionMismatch:
      expr: up == 4
      labels:
        severity: critical
  other-service:
    OtherAlert:
      expr: asd
