alerts:
  etcd:
    etcdInsufficientMembers:
      annotations:
        message: 'bum-bum'
  kubernetes-system:
    KubeVersionMismatch:
      expr: up == 4
      labels:
        severity: critical
  other-service:
    OtherAlert:
      expr: asd
alert_flags:
  etcd: false
  kubernetes-system: true
  kubernetes-absent: true
  other-service: false
