apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- $root := . }}
  {{- $result_alerts := dict }}
  {{- range $path, $bytes := .Files.Glob "files/*.yaml" }}
    {{- $alertfile :=  $root.Files.Get $path | fromYaml }}
    {{- $result_alerts = merge $alertfile $result_alerts}}
  {{- end }}
  {{- $result_alerts = merge $.Values.alerts $result_alerts.alerts }}
  groups:
  {{- range $service, $attrib := $result_alerts }}
    {{- if index $.Values.alert_flags $service }}
  - name: {{ $service }}
    rules:
      {{- range $alertname, $alertvalues := $attrib }}
    - alert: {{ $alertname -}}
        {{ $alertvalues | toYaml | nindent 6 -}}
      {{- end }}
    {{- end }}
  {{- end }}
