apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- $root := . }}
  groups:
  {{- range $path, $bytes := .Files.Glob "files/*.yaml" }}
    {{- $alertfile :=  $root.Files.Get $path | fromYaml }}
    {{- range $service, $attrib := $alertfile.alerts }}
  - name: {{ $service -}}
    rules:
      {{- range $alertname, $alertvalues := $attrib }}

        {{- if hasKey $.Values.alerts $service}}
          {{- $overrides := default (dict ) index (index $.Values.alerts $service) $alertname }}
        {{- else }}
          {{- $overrides := dict }}
        {{ end }}

    - alert: {{ $alertname -}}
        {{ toYaml (merge $overrides $alertvalues) | nindent 6 -}}
      {{- end }}
    {{- end }}
  {{- end }}
