apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- $root := . }}
  groups:
  {{- range $path, $bytes := .Files.Glob "files/*.yaml" }}
    {{- $alertfile :=  $root.Files.Get $path | fromYaml }}
    {{- range $service, $attrib := $alertfile.alerts }}
  - name: {{ $service -}}
    rules:
      {{- range $alertname, $alertvalues := $attrib }}
        {{ $override := index $.Values.alerts $service $alertname}}
    - alert: {{ $alertname -}}
        {{ merge $override $alertvalues | toYaml | nindent 6 -}}
      {{- end }}
    {{- end }}
  {{- end }}
